using UnityEngine;
using System.Collections;

public class FollowPlayer : MonoBehaviour
{
    TimeCount timer;
    GameUIManager uiManager;

    public Transform player; // üéØ R√©f√©rence au personnage
    private float fixedY;    // Hauteur fixe du plane

    private Animator animator;

    ScoreManager scoreManager;

    void Start()
    {
        scoreManager = GameObject.Find("Canvas").GetComponent<ScoreManager>();

        // R√©cup√©rer correctement le script TimeCount dans la sc√®ne
        timer = FindFirstObjectByType<TimeCount>();  // Trouve le script TimeCount dans la sc√®ne
        if (timer == null)
        {
            Debug.LogError("TimeCount script not found in the scene!");
        }

        // R√©cup√©rer correctement le script GameUIManager dans la sc√®ne
        uiManager = FindFirstObjectByType<GameUIManager>();  // Trouve le script GameUIManager dans la sc√®ne
        if (uiManager == null)
        {
            Debug.LogError("GameUIManager script not found in the scene!");
        }

        // Stocker la hauteur initiale du plane
        fixedY = transform.position.y;
    }


    void Update()
    {

        // Suivre le joueur en X et Z, mais garder Y fixe
        transform.position = new Vector3(player.position.x, fixedY, player.position.z);
    }

    void OnTriggerEnter(Collider other)
    {
        if (other.gameObject.CompareTag("Player"))
        {
            animator = other.gameObject.GetComponent<Animator>();

            // launch animation
            if (animator != null)
            {
                animator.SetTrigger("Fall");
            }
            else
            {
                Debug.LogError("‚ùå Animator component not found on the player!");
            }

            if (timer != null) // V√©rifie que timer n'est pas null avant d'y acc√©der
            {
                timer.SetRunning(false);
                float finalTime = timer.GetElapsedTime();
                StartCoroutine(waitAndReload(scoreManager.GetScore(), finalTime));
            }
            else
            {
                Debug.LogError("TimeCount script not found in the scene!");
            }
        }
    }

    IEnumerator waitAndReload(int score, float finalTime)
    {
        yield return new WaitForSeconds(3f);
        uiManager.ShowResults(score, finalTime);
    }
}
